name: ci-tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/**
      - internal/**
  pull_request:
    branches:
      - main
    paths:
      - api/**
      - internal/**

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Config
        run: |
          go get github.com/cloudflare/cfssl/cmd/... 
          export PATH=${PATH}:${HOME}/go/bin
          make gencert
          make genacl
      - name: Test Log
        working-directory: ./internal/log
        run: |
          go test -v -race -coverprofile=profile.out -covermode=atomic
          cat profile.out >> ${HOME}/coverage.txt
      - name: Test Server
        working-directory: ./internal/server
        run: |
          go test -v -race -coverprofile=profile.out -covermode=atomic
          cat profile.out >> ${HOME}/coverage.txt
      - name: Test Service discovery
        working-directory: ./internal/discovery
        run: |
          go test -v -race -coverprofile=profile.out -covermode=atomic
          cat profile.out >> ${HOME}/coverage.txt 
      - name: Test Agent (with raft consensus)
        working-directory: ./internal/agent
        run: |
          go test -v -race -coverprofile=profile.out -covermode=atomic
          cat profile.out >> ${HOME}/coverage.txt 
      - name: Obtain code coverage report
        run: cp ${HOME}/coverage.txt coverage.out
      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v2

