name: ci-tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - api/**
      - internal/**
  pull_request:
    branches:
      - main
    paths:
      - api/**
      - internal/**

jobs:
  test-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd internal/log && go test -race
 
