name: docker-image
on:
  workflow_dispatch:

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          export IMAGE_NAME="ghcr.io/arindas/proglog:${GITHUB_REF##*/}"
          docker build -t ${IMAGE_NAME} .
      - name: Authenticate to github docker registry
        run: |
          docker login ghcr.io -u arindas -p ${{ secrets.GH_DOCKER_TOCKEN }}
      - name: Push docker image
        run: docker push 

