name: docker-image
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: |
          export IMAGE_PREFIX="ghcr.io/arindas/proglog"
          docker build -t "${IMAGE_PREFIX}:${GITHUB_REF##*/}" "${IMAGE_PREFIX}:latest" .
      - name: Authenticate to github docker registry
        run: |
          docker login ghcr.io -u arindas -p ${{ secrets.GH_DOCKER_TOCKEN }}
      - name: Push docker image
        run: |
          docker push -a "ghcr.io/arindas/proglog"

